spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: remoteaddr_route
        uri: https://www.baidu.com
        predicates:
        - Path=/foo/{segment}
      - id: trace_customer
        uri: lb://TRACE
        predicates:
        - Path=/trace/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
server:
  port: 10000


eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: 172.30.201.25:10000
  client:
    health:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug